### Grading
- Total: **1.5 points**
- **5 tasks × 0.30 each = 1.5**
- Autotests award full points per task if all checks pass.

**Important:** Use the exact variable names from each template.
Some tasks require setting a random seed for reproducibility.


## Task 1 — Arrays & Indexing
Create an array of integers from **1 to 30** (inclusive).
1) Select all **even** numbers → `evens`
2) Select **every third** number → `every_third`
3) Build a subarray consisting of elements **from the 10th to the 15th** (inclusive, 1-based indexing) → `sub_10_15`


In [2]:
import numpy as np
arr = np.arange(1, 31)
evens = arr[arr % 2 == 0]

every_third = arr[arr % 3 ==1]

sub_10_15 = np.arange(10, 16)

In [21]:
# Autotest Task 1
assert arr[0]==1 and arr[-1]==30 and arr.size==30
assert evens.size==15 and (evens%2==0).all()
assert every_third[0]==1 and every_third[1]==4 and every_third.size==10
assert sub_10_15[0]==10 and sub_10_15[-1]==15 and sub_10_15.size==6
print("Task 1 passed (0.3 points)")

Task 1 passed (0.3 points)


## Task 2 — Matrix Slicing
Generate a **6×6** matrix with values from **1 to 36** (row-major) → `M`.
1) Extract the **center 3×3** submatrix → `center_3x3`
2) Extract the **main diagonal** → `main_diag`
3) **Swap** the first and the last **rows** → `M_swapped`


In [38]:
M = np.arange(1, 37).reshape(6, 6)
center_3x3 = M[1:4, 1:4]
main_diag = M.diagonal()
M_swapped = M.copy()
M_swapped[[0, -1]] = M[[-1, 0]]
M_swapped

array([[31, 32, 33, 34, 35, 36],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5,  6]])

In [39]:
assert M.shape==(6,6)
assert M[0,0]==1 and M[-1,-1]==36
assert center_3x3.shape==(3,3)
assert main_diag.size==6
assert (M_swapped[0]==M[-1]).all()
print("Task 2 passed (0.3 points)")

Task 2 passed (0.3 points)


## Task 3 — Grade Statistics (Aggregations + Filtering)
Create **20 random integer** grades from 0 to 100 using a fixed **seed=42** for reproducibility:
1) Compute **mean** → `mean`, **min** → `min_v`, **max** → `max_v`
2) Find the **index of the lowest** grade → `argmin_idx`
3) Count how many students scored **above the mean** → `above_mean_count`


In [48]:
np.random.seed(42)

grades = np.random.randint(0, 101, size=20)

mean = grades.mean()
min_v = grades.min()
max_v = grades.max()

argmin_idx = grades.argmin()

above_mean_count = (grades > mean).sum()

In [49]:
# Autotest Task 3
assert grades.size==20
for g in grades:
    assert g >= min_v
    assert g <= max_v
assert 0 <= argmin_idx < len(grades)
_py_mean = sum(int(x) for x in grades.tolist()) / len(grades)
assert abs(float(mean) - _py_mean) < 1e-9
_cnt = 0
for x in grades:
    if x > mean:
        _cnt += 1
assert int(above_mean_count) == _cnt
assert grades[argmin_idx] == min_v

print("Task 3 passed (0.3 points)")

Task 3 passed (0.3 points)


## Task 4 — Broadcasting & Normalization
Using broadcasting, create a **10×10 multiplication table**:
1) Build the table via broadcasting → `table`
2) Compute the **sum of all elements** → `total_sum`
3) **Normalize** the table so that each value is divided by the **maximum element** → `normalized`


In [59]:
row = np.arange(1, 11)
col = np.arange(1, 11).reshape(-1, 1) 
table = row * col

total_sum = table.sum()

normalized = table / table.max()

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ],
       [0.03, 0.06, 0.09, 0.12, 0.15, 0.18, 0.21, 0.24, 0.27, 0.3 ],
       [0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ],
       [0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.06, 0.12, 0.18, 0.24, 0.3 , 0.36, 0.42, 0.48, 0.54, 0.6 ],
       [0.07, 0.14, 0.21, 0.28, 0.35, 0.42, 0.49, 0.56, 0.63, 0.7 ],
       [0.08, 0.16, 0.24, 0.32, 0.4 , 0.48, 0.56, 0.64, 0.72, 0.8 ],
       [0.09, 0.18, 0.27, 0.36, 0.45, 0.54, 0.63, 0.72, 0.81, 0.9 ],
       [0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.6 , 0.7 , 0.8 , 0.9 , 1.  ]])

In [55]:
# Autotest Task 4
import numpy as _np
assert table.shape==(10,10)
assert total_sum==3025
assert _np.isclose(normalized.max(),1)
print("Task 4 passed (0.3 points)")

Task 4 passed (0.3 points)


## Task 5 — Filtering with `np.where`
Generate **1000 random integers** from **-50 to 50** with a fixed seed=7:
1) Select all **positive** values → `positives`
2) Replace **negative** values with **0** using `np.where` → `replaced`
3) Create array of **unique** values (sorted) → `unique_vals`


In [60]:
np.random.seed(7)
data = np.random.randint(-50, 51, 1000)
positives = data[data > 0]

replaced = np.where(data < 0, 0, data)

unique_vals = np.unique(replaced)

In [61]:
# Autotest Task 5
import numpy as _np
assert data.size==1000
assert (positives>0).all()
assert (replaced>=0).all()
assert _np.array_equal(unique_vals, _np.unique(replaced))
print("Task 5 passed (0.3 points)")

Task 5 passed (0.3 points)


In [3]:

arr = np.random.randint(0,100, 5)
arr

array([57, 28, 50, 13, 68])